version: '3.7'

services:
    logstash:
        image: docker.elastic.co/logstash/logstash:7.8.1
        container_name: logstash
        volumes:
          - ./temp/logstash.yml:/usr/share/logstash/config/logstash.yml
          - ./temp/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
        ports:
          - 5044:5044