version: '2.2'
services:
  ls01:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: ls01
    volumes:
      - ./temp/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./temp/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    environment:
      ELASTICSEARCH_URL: http://${REMOTE_ES_HOST}:${REMOTE_ES_PORT}
      ELASTICSEARCH_HOSTS: http://${REMOTE_ES_HOST}:${REMOTE_ES_PORT}
      AGENT_UUID: ${AGENT_UUID}
    networks:
      - green

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  green:
    driver: bridge

