version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - green

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - green
    depends_on:
      - es01

  ls01:
    image: logstash-gps:latest
    container_name: ls01
    volumes:
      - ./temp/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./temp/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../secret/kropotkin-gc-key.json:/usr/share/logstash/kropotkin-gc-key.json
    ports:
      - 5044:5044
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - green
    depends_on:
      - es01

  zeek:
    image: zeek-local:latest
    container_name: zeek
    network_mode: host
    environment:
      LOGSTASH_URL: http://127.0.0.1:5044
    volumes:
      - ./temp/zeek-filebeat.yml:/etc/filebeat/filebeat.yml
      - ./temp/local.zeek:/opt/zeek/share/zeek/site/local.zeek
      - ./temp/sumstats-kropotkin.zeek:/opt/zeek/share/zeek/site/sumstats-kropotkin.zeek
      - ./temp/node.cfg:/opt/zeek/etc/node.cfg
    depends_on:
      - ls01
    cap_add:
      - NET_ADMIN

  wazuh:
    image: wazuh/wazuh:latest
    container_name: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    network_mode: host
    environment:
      LOGSTASH_URL: http://127.0.0.1:5044
    volumes:
      - ./temp/wazuh-filebeat.yml:/etc/filebeat/filebeat.yml
      - ./temp/wazuh-template.json:/etc/filebeat/wazuh-template.json
    depends_on:
      - ls01

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  green:
    driver: bridge

